# Generated by Django 3.0.3 on 2020-07-18 01:53

from django.db import migrations, models
import subscriptions.plans


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.IntegerField(choices=[(2, 'TRIAL'), (199, 'BASIC'), (399, 'PREMIUM'), (799, 'DIAMOND')], default=subscriptions.plans.SubscriptionPlan['BASIC'], help_text='amount for searches'),
        ),
    ]
